DATEBASE:
  TYPE: 'mysql'
  HOST: 'localhost'
  PORT: 3306
  USERNAME: 'bit'
  PASSWORD: '123456'
  DATEBASE: 'blog'

JWT_SECRET: 'test123'
JWT_EXPIRES_IN: '7d'
SECRET_KEY: 'test_key'
USER_SECRET_KEY: 'key'
